name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      # Correr tests del backend (Node.js)
      - name: Instalar y testear backend
        run: |
          cd backend
          npm ci    # Instalación limpia para entorno CI
          npm test  # Ejecuta las pruebas automatizadas

      # Correr tests del frontend (Vite + React)
      # - name: Instalar y testear frontend
      #   run: |
      #     cd frontend
      #     npm ci
      #     npm test

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construcción imagen backend (Node.js)
      - name: Build imagen backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-inventario:latest ./backend

      # Construcción imagen frontend (Vite + React)
      - name: Build imagen frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:latest ./frontend

      # Push de imágenes a Docker Hub
      - name: Push backend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-inventario:latest

      - name: Push frontend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:latest
