name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del c칩digo
      uses: actions/checkout@v3

    - name: Configurar Docker
      uses: docker/setup-buildx-action@v3

    - name: Login a Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construcci칩n imagen backend (Node.js)
    - name: Build imagen backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-inventario:latest ./backend

    # Construcci칩n imagen frontend (React)
    - name: Build imagen frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:latest ./frontend

    # Correr tests del backend (Node.js)
    - name: Correr tests del backend
      run: |
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/backend-inventario:latest npm test

    # Correr tests del frontend (React)
    - name: Correr tests del frontend
      run: |
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:latest npm test -- --watchAll=false

    # Push de im치genes a Docker Hub
    - name: Push backend
      run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-inventario:latest

    - name: Push frontend
      run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:latest
