name: CI/CD Pipeline Temporal

on:
  push:
    branches: [ "merge-test-fernandoQA" ]
  pull_request:
    branches: [ "merge-test-fernandoQA" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ secrets.TEST_DB_DATABASE }}
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar y testear backend
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: ${{ secrets.TEST_DB_USER }}
          DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.TEST_DB_DATABASE }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo "--- Instalando y testeando Backend ---"
          cd backend
          npm ci
          npm run test -- --coverage

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build imagen backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-inventario:merge-test-fernandoQA ./backend

      - name: Build imagen frontend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:merge-test-fernandoQA ./frontend

      - name: Push imagen backend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-inventario:merge-test-fernandoQA

      - name: Push imagen frontend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:merge-test-fernandoQA
