name: CI - Build Producción (main)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push imágenes con tag latest
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-inventario:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-inventario:latest

          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:latest
     
      # El despliegue es automático vía Vercel al hacer push a 'main'


