name: CI - Test & Docker Push (ci-test)

on:
  push:
    branches: [ "ci-test" ]
  pull_request:
    branches: [ "ci-test" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar dependencias backend
        run: |
          cd backend
          npm ci

      - name: Inicializar base de datos
        run: |
          sudo apt-get install -y postgresql-client
          PGPASSWORD=${{ secrets.DB_PASSWORD }} \
          psql -h localhost -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -f ./backend/db/schema.sql

      - name: Ejecutar tests backend
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          PORT: ${{ secrets.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
        run: |
          cd backend
          npm run test -- --coverage

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push imágenes con tag ci-test
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-inventario:ci-test ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-inventario:ci-test

          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:ci-test ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:ci-test
