name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar y testear backend
        run: |
          cd backend
          npm ci
          npm test
          
    # - name: Instalar y testear frontend
    #   run: |
    #     cd frontend
    #     npm ci
    #     npm test

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build imagen backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-inventario:latest ./backend

      - name: Build imagen frontend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:latest ./frontend

      - name: Push imagen backend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-inventario:latest

      - name: Push imagen frontend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:latest

      # El despliegue de la app se realiza automáticamente en Vercel.
      # Cuando se hace push a 'main', Vercel detecta los cambios y realiza el deploy automáticamente.
      # !!!!!!!!EN TEORÍA !!!!!!No es necesario configurar un paso adicional de despliegue aquí.
