name: CI - Build Production (main)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Definir tag semántico o por fecha (prod)
        run: echo "TAG=prod-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push imágenes producción
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-inventario:${{ env.TAG }} ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-inventario:${{ env.TAG }}

          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:${{ env.TAG }} ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-inventario:${{ env.TAG }}
     
      # El despliegue es automático vía Vercel al hacer push a 'main'


