name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Login a Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build de imagen Docker
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mi-app:latest .

    - name: Correr tests (ejemplo con Python)
      run: |
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/mi-app:latest pytest tests/

    - name: Push de imagen a Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mi-app:latest
